version: '3.0'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: 7123456
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis
    ports:
      - "6379:6379"